### ISSUE TITLE
Is it possible to serialize scheduled messages using ProtoBuf serializer?

### ISSUE THREAD

**Issue by object** [Horusiath/Akka.Persistence.Reminders#10]
I checked the source code, and apparently the library uses serializer resolved via Akka API (FindSerializerFor). Does this mean that if we configure in Akka HOCON ProtoBuf serializer for our message type, the library will use it?

**Comment by Horusiath** [comment]
Sorry for late response. Answer is yes, this library uses the same serialization pattern as most of the core Akka.NET libraries. It's basically serializing custom user payload using pair `(serializer_id, payload)`, where `serializer_id` is a number configured in HOCON serializers section, and `payload` is a byte array produced by corresponding serializer.

**Comment by object** [comment]
Thank you! Yes, we already tested using Protobuf and everything worked. Good job!
