### ISSUE TITLE
Unusual repo size

### ISSUE THREAD

**Issue by Lutando** [Horusiath/Akka.Persistence.Reminders#4]
More of an observation than an issue, but when I was cloning this repository it took over 100MiB down the wire, and I have no idea why. 

Doesnt have that many commits nor files. Very strange

**Comment by Horusiath** [comment]
I guess, that somewhere back in the history of this repo, there might been an issue with .gitignore, which potentially could cause some exec files to be included. I guess [this is the PR](https://github.com/Horusiath/Akka.Persistence.Reminders/commit/2c43b968535f13983ef5081ca35b97b3af2313f4), that removed them.
